"""This module holds utilties that can be reused across other modules, for
example the UTC date/time stamp.
"""

from pathlib import Path


def compare_files(file1: Path, file2: Path, ignore_words: list[str]) -> bool:
    """Compares two files, line-by-line, ignoring lines that are in the list
    of `ignore_words`.

    Args:
        file1: Path to the first file for comparison.
        file2: Path to the second file for comparison.
        ignore_words: List of words that cause a particular line for comparison
            to be ignored.  Use an empty list for strict word-by-word
            in each line type of comparison.  Use a non-empty list, e.g.,
            ["date", "time"] to ignore lines with these words, as they may
            differ from file to file.

    Returns:
        True is the two files are the same (up to any allowed differences in
        the ignore_words list), False if the two files are different.

    """

    with open(file=file1, mode="r", encoding="utf-8") as fa:
        with open(file=file2, mode="r", encoding="utf-8") as fb:
            dba = fa.readlines()
            dbb = fb.readlines()

            if len(dba) == len(dbb):
                for k, line in enumerate(dba):
                    if line != dbb[k]:
                        # if "Autogenerated" in line:
                        iw_in_fa_line = [iw in line for iw in ignore_words]
                        iw_in_fb_line = [iw in dbb[k] for iw in ignore_words]
                        in_either_line = iw_in_fa_line + iw_in_fb_line
                        # if any(iw in [line + dbb[k]] for iw in ignore_words):
                        if any(in_either_line):
                            # skip comparison of the ignore_words case(s)
                            print("Skip comparison of word in ignore_word.")
                        else:
                            print(f"Files differ at line {k+1}:")
                            print(f"\t file1: {line}")
                            print(f"\t file2: {dbb[k]}")
                            return False

            else:
                print("Files have non-equal line length.")
                print("Line-by-line comparison not performed.")
                return False

    return True  # files are the same
