# ------------------------------------------------------------------------------
# The autotwin.mesh Python module, version 0.0.7,
# https://github.com/autotwin/mesh/
# autogenerated this file on 2024-06-06_UTC_14_17_32_921702
# from the yml recipe file:
# /Users/chovey/autotwin/mesh/tests/files/letter_f_autotwin.yml
# ------------------------------------------------------------------------------
BEGIN SCULPT
  nelx = 3
  nely = 5
  nelz = 4
  xscale = 0.1
  yscale = 0.1
  zscale = 0.1
  xtranslate = -0.15
  ytranslate = -0.25
  ztranslate = -0.2
  gen_sidesets = variable
  stair = 1
  input_spn = /Users/chovey/autotwin/mesh/tests/files/letter_f_autotwin.spn
  exodus_file = /Users/chovey/autotwin/mesh/tests/files/letter_f_autotwin
  spn_xyz_order = 5
END SCULPT
